### ISSUE TITLE
Error in Compilation of dehaze

### ISSUE THREAD

**Issue by abhi-kumar** [zeyuanxy/course-media-computing#1]
Please change the makefile command 
from 
   $(CXX) $(CXXFLAGS)  $(LIBS) $+ -o $@

to 		
   $(CXX) $(CXXFLAGS) $+ -o $@ $(LIBS)

for correct compilation of the code.

**Comment by zeyuanxy** [comment]
Done, Thanks very much! @abhi-kumar
